from src.Assignment_2.utils import *

spark = spark_session()
user_df = create_df(spark)
user_df.show()
select_col = select_df(user_df)
select_col.show()
user_new_df = add_column(user_df)
user_new_df.show()
salary_df = salary_change(user_df)
salary_df.show()
type_changed_df = change_type(user_df)
type_changed_df.printSchema()
salary_bonus = Salary_bonus(user_df)
salary_bonus.show()
nested_df = nested_col(user_df)
nested_df.show()
nested_df.printSchema()
filtered_df = name_filter(user_df)
print(filtered_df)
user_new_df = add_column(user_df)
user_new_df.show()
droped_df = drop_column(user_new_df)
droped_df.show()
dis_df = distinct_column(user_df)
dis_df.show()
